# EHT Simulator - Default Parameters
# This file contains all default values for reference.
# Only specify values you want to change from defaults.

[general]
t_end = 48
dt = 0.1
random_seed = 0
N_init = 30
N_max = 80
N_emt = 5
w_init = 80
h_init = 5
mu = 0.2
n_substeps = 30
alg_dt = 0.01
w_screen = 70
h_screen = 23.333333333333332
p_div_out = 1.0
curvature = 0.06

[cell_prop]
apical_junction_init = 0.0
max_basal_junction_dist = 2.0
basal_daming_ratio = 1.0
basal_membrane_repulsion = 0.0
cytos_init = 0.0
diffusion = 0.2

[cell_types.control]
name = "control"
R_hard = 0.4
R_hard_div = 0.7
R_soft = 1.2
dur_G2 = 0.5
dur_mitosis = 0.5
k_apical_junction = 5.0
k_cytos = 5.0
max_cytoskeleton_length = 0.0
run = 0.0
running_speed = 1.0
running_mode = 0
stiffness_apical_apical = 2.0
stiffness_apical_apical_div = 4.0
stiffness_nuclei_apical = 3.0
stiffness_nuclei_basal = 2.0
stiffness_repulsion = 2.0
stiffness_straightness = 5.0
INM = 0.0
hetero = false

[cell_types.control.color]
r = 30
g = 100
b = 20

[cell_types.control.lifespan]
min = 5.5
max = 6.5

[cell_types.control.events.time_A]
min = 1e308
max = 1e308

[cell_types.control.events.time_B]
min = 1e308
max = 1e308

[cell_types.control.events.time_S]
min = 1e308
max = 1e308

[cell_types.control.events.time_P]
min = 1e308
max = 1e308

[cell_types.emt]
name = "emt"
R_hard = 0.4
R_hard_div = 0.7
R_soft = 1.2
dur_G2 = 0.5
dur_mitosis = 0.5
k_apical_junction = 1.0
k_cytos = 5.0
max_cytoskeleton_length = 0.0
run = 0.0
running_speed = 1.0
running_mode = 0
stiffness_apical_apical = 2.0
stiffness_apical_apical_div = 4.0
stiffness_nuclei_apical = 3.0
stiffness_nuclei_basal = 2.0
stiffness_repulsion = 4.0
stiffness_straightness = 2.0
INM = 0.0
hetero = true

[cell_types.emt.color]
r = 128
g = 0
b = 128

[cell_types.emt.lifespan]
min = 5.5
max = 6.5

[cell_types.emt.events.time_A]
min = 3
max = 12

[cell_types.emt.events.time_B]
min = 3
max = 12

[cell_types.emt.events.time_S]
min = 1e308
max = 1e308

[cell_types.emt.events.time_P]
min = 1e308
max = 1e308
